### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by naodya** [Ethiopia-COVID19/Project-Surveillance-Forms#12]
Form routes fail unless tab links are use.

Steps to replicate:

- Goto http://forms.ethiopia-covid19.com
- Click one of the form links on top of the page
- Refresh page 

Or directly open one of the forms
- http://forms.ethiopia-covid19.com/medical-form

![image](https://user-images.githubusercontent.com/1115720/78604190-68786600-7827-11ea-8453-8c1ac9fcef8e.png)

**Comment by antxaddis** [comment]
I think this is issue with S3.

https://stackoverflow.com/questions/50727884/react-app-routes-issue-when-deployed-to-aws

Asked Nati Abebe to fix.

**Comment by antxaddis** [comment]
This is now fixed through S3 config change.
